- name: Install and configure MySQL
  hosts: all
  become: true

  pre_tasks:

    - name: Add MySQL repository
      ansible.builtin.yum_repository:
        name: mysql57-community
        description: MySQL 5.7 Community repo
        baseurl: https://repo.mysql.com/yum/mysql-5.7-community/el/7/x86_64/
        gpgcheck: false
      when: ansible_os_family == "RedHat"

    - name: Override variables for MySQL (RedHat).
      ansible.builtin.set_fact:
        mysql_daemon: mysqld
        mysql_packages: ['mysql-community-server']
        mysql_log_error: /var/log/mysqld.log
        mysql_syslog_tag: mysqld
        mysql_pid_file: /var/run/mysqld/mysqld.pid
        mysql_socket: /var/lib/mysql/mysql.sock
        mysql_slow_query_log_file: /var/log/mysql-slow.log
        mysql_slow_query_time: 2
        mysql_slow_query_log: true
        mysql_log_queries_not_using_indexes: true
        mysql_config_file: /etc/my.cnf
        mysql_config_include_dir: /etc/my.cnf.d
        mysql_supports_innodb_large_prefix: true
      when: ansible_os_family == "RedHat"

  roles:
    - role: geerlingguy.mysql
      become: true
      vars:
        mysql_port: "3306"
        mysql_bind_address: '0.0.0.0'
        mysql_packages:
          - mysql-community-server
        mysql_enabled_on_startup: true
        mysql_root_user: root
        mysql_root_password: "{{ lookup('file', 'secrets/root_pwd.txt') }}"
        mysql_root_password_update: true
        mysql_databases:
          - name: abnmo
            encoding: utf8
            collation: utf8_general_ci
        mysql_users:
          - name: abnmo_admin
            host: "%"
            password: "{{ lookup('file', 'secrets/abnmo_admin_pwd.txt') }}"
            priv: "abnmo.*:ALL"
            state: present
          - name: abnmo_dev
            host: "%"
            password: "{{ lookup('file', 'secrets/abnmo_dev_pwd.txt') }}"
            priv: "abnmo.*:DELETE, INSERT, SELECT, UPDATE"
            state: present
