---
- name: Install and configure MySQL
  hosts: all
  become: yes

  tasks:
    - name: Add MySQL repository
      yum:
        name: https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm
        state: present

    - name: Install MySQL
      yum:
        name: mysql-community-server
        state: present

    - name: Start MySQL service
      systemd:
        name: mysqld
        state: started
        enabled: yes

    - name: Get temporary MySQL root password
      command: grep 'temporary password' /var/log/mysqld.log
      register: temp_pass_output
      changed_when: false

    - name: Set MySQL root password
      mysql_user:
        name: root
        host: localhost
        password: "pirarucu"
        login_password: "{{ temp_pass_output.stdout | regex_search('root@localhost: (.*)', '\\1') }}"
        check_implicit_admin: true
        state: present
